Formatting changes

diff --git a/t/runtests b/t/runtests
--- a/t/runtests
+++ b/t/runtests
@@ -5,7 +5,10 @@ for test in *.in
     tname=$(basename $test .in)
     ../a.out < $tname.in > $tname.out 2> $tname.err
     # Check standard output
-    diff $tname.out $tname.out.ref
+    if ! diff $tname.out $tname.out.ref
+      then
+        echo "FAIL: $tname"
+      fi
     # Check error output
     if [ -f $tname.err.ref ]
       then
